artes/artes/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from artes import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

artes/cart/urls.py
from .views import *
from django.urls import path

app_name='cart'
urlpatterns=[
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/<change>/', add_cart, name='add_cart'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('clear/', cart_clear, name='cart_clear')
]

artes/shop/urls.py
from django.urls import path
from .views import *
from rest_framework.authtoken import views

app_name='shop'
urlpatterns = [
    path('category/', category, name='category'),
    path('product/', product, name='product'),
    path('login/', log_in, name='login'),
    path('token_login/', token_login, name='tokenlogin'),
    path('logout', log_out, name='logout'),
    path('register/', register, name='register')
]

artes/shop/models.py
from PIL import Image
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey
from imagekit.models.fields import ImageSpecField
from imagekit.processors import ResizeToFit
from pilkit.processors import Adjust


class Product(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')
    photo = models.ImageField(
        upload_to = 'photos/%Y/%m/%d/',
        verbose_name='Фото',
        null=True,
        blank=True
    )
    photo_s = ImageSpecField(
        [Adjust(contrast=1.2, sharpness=1.1),
         ResizeToFit(50,50)],
        source='photo',
        format='JPEG',
        options={'quality':90}
    )
    photo_m = ImageSpecField(
        [Adjust(contrast=1.2, sharpness=1.1),
         ResizeToFit(300, 200)],
        source='photo',
        format='JPEG',
        options={'quality': 90}
    )
    photo_l = ImageSpecField(
        [Adjust(contrast=1.2, sharpness=1.1),
         ResizeToFit(640, 480)],
        source='photo',
        format='JPEG',
        options={'quality': 90}
    )
    cat = models.ForeignKey('Category', on_delete = models.PROTECT, verbose_name='Категория')
    subcat = TreeForeignKey('Subcategory', on_delete=models.PROTECT, verbose_name='Подкатегория')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product', kwargs = {'product_slug' : self.slug})

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['id']

class Category(MPTTModel):
    name = models.CharField(max_length = 100, db_index = True, verbose_name='Категория')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    photo = models.ImageField(
        upload_to='photos/%Y/%m/%d/',
        verbose_name='Фото',
        null=True,
        blank=True
    )
    parent = TreeForeignKey(
        'self',
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        db_index=True,
        related_name='parents',
        verbose_name='Пока не знаю')
    # level = models.PositiveIntegerField(default=0)
    # lft = models.PositiveIntegerField(default=0)
    # rght = models.PositiveIntegerField(default=1)
    # tree_id = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs = {'cat_slug' : self.slug})

    # class MPTTMeta:
    #     order_insertion_by = ['name']

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['id']

class Subcategory(MPTTModel):
    name = models.CharField(max_length = 100, db_index = True, verbose_name='Подкатегория')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    photo = models.ImageField(
        upload_to='photos/%Y/%m/%d/',
        verbose_name='Фото',
        null=True,
        blank=True
    )
    parent = TreeForeignKey(
        'Category',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children',
        db_index=True,
        verbose_name='Родительская категория')
    # level = models.PositiveIntegerField(default=1)
    # lft = models.PositiveIntegerField(default=0)
    # rght = models.PositiveIntegerField(default=2)
    # tree_id = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('subcategory', kwargs = {'subcat_slug' : self.slug})

    class Meta:
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'
        ordering = ['id']

    class MPTTMeta:
        order_insertion_by = ['name']

artes/shop/forms.py
from django.contrib.auth import forms
from django.contrib.auth.models import User
from django import forms as fforms



class RegisterForm(forms.UserCreationForm):
    class meta:
        model=User
        fields=('username', 'password1', 'password2')

class LoginForm(forms.AuthenticationForm):
    class meta:
        model=User,
        fields=('username', 'password')

artes/shop/views.py
from time import sleep

from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template import RequestContext
from django.urls import reverse_lazy

from .forms import *
from .models import *
from cart.forms import CartAddProductForm
from django.contrib.auth.models import User

menu = [{'title':'Вход', 'url_name':'shop:login'},
        {'title':'Регистрация', 'url_name':'shop:register'},
        {'title':'Категории товаров', 'url_name':'shop:category'},
        {'title':'Товары', 'url_name':'shop:product'},
        {'title':'Корзина', 'url_name':'cart:cart_detail'},
]
def category(request):
    cat_list=Category.objects.all()
    subcat_list=Subcategory.objects.all()
    paginator=Paginator(cat_list, 3)
    page_num=request.GET.get('page')
    page_obj=paginator.get_page(page_num)
    return render(
        request,
        'category.html',
        {'title':'Список категорий',
         'subcat_list':subcat_list,
         'page_obj':page_obj,
         'menu':menu
         }
    )

def product(request):
    product_list=Product.objects.all()
    paginator=Paginator(product_list, 3)
    page_num=request.GET.get('page')
    page_obj=paginator.get_page(page_num)
    cart_add_form=CartAddProductForm
    return render(
        request,
        'product.html',
        {'title':'Список товаров',
         'product_list':product_list,
         'page_obj':page_obj,
         'cart_add_form':cart_add_form,
         'menu': menu,
         'is_auth':request.user.is_authenticated
         }
    )

def register(request):
    form=RegisterForm(data=request.POST)
    if form.is_valid():
        User.objects.create_user(
            username=form.cleaned_data['username'],
            email=form.cleaned_data['username']+'@mail.ru',
            password=form.cleaned_data['password1'],
        )
        return redirect('shop:login')
    return render(
        request,
        'register.html',
        {'title':'Регистрация',
         'form':form,
         'menu':menu
        }
    )

def log_in(request):
    form=LoginForm(data=request.POST)
    print('form.is_valid:', form.is_valid())
    if form.is_valid():
        user=authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        login(request, user)
    return render(
        request,
        'login.html',
        {
            'title':'Вход',
            'form':form,
            'menu':menu

        },
    )

def log_out(request):
    print(request.user.is_authenticated)
    logout(request)
    print(request.user.is_authenticated)
    return redirect('shop:login')

def token_login(request):
    return HttpResponse('Authorization: Token 7000a2ebdef80859cf59c3553f55de71a30a6dae')

artes/shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
{% block mainmenu %}
    {% for m in menu %}
		<span>
            <h2><a href="{% url m.url_name %}">{{m.title}}</a></h2>
        </span>
	{% endfor %}
				</ul>
				<div class="clear"></div>
			</div>
{% endblock mainmenu %}

<h1>{{ title }} :</h1>
    <br>
    <br>
    {% block body %}
    {% endblock body %}

    {% if page_obj.has_other_pages %}
        <nav class="pagination">
            <ul>
                <span>
                    <a href="?page=1">&lt;<</a>
                </span>

                {% if page_obj.has_previous %}
                    <span>
                        <a href="?page={{page_obj.previous_page_number}}">&lt;</a>
                    </span>
                {% endif %}

                {% for p in page_obj.paginator.page_range %}
                    {% if page_obj.number == p %}
                        <span>{{ p }}</span>
                    {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                        <span>
                            <a href="?page={{ p }}">{{ p }}</a>
                        </span>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <span>
                        <a href="?page={{page_obj.next_page_number}}">&gt;</a>
                    </span>
                {% endif %}

                <span>
                    <a href="?page={{page_obj.paginator.num_pages}}">>></a>
                </span>
            </ul>
        </nav>
    {% endif %}

</body>
</html>

artes/shop/templates/category.html
{% extends 'base.html' %}

{% block body %}
{% for c in page_obj %}
    <ul>
        <li>
            {{ c.name }}
            {% for s in subcat_list %}
                {% if s.parent_id == c.id %}
                    <ul>
                        <li>
                            {{ s.name }}
                        </li>
                    </ul>
                {% endif %}
            {% endfor %}
        </li>
    </ul>
{% endfor %}
{% endblock body %}

artes/shop/templates/login.html
{% extends 'base.html'%}

{% block body %}

<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Вход</button>
</form>
<form action="{% url 'shop:logout' %}" method="post">
    {% csrf_token %}
    <input type='submit' value='Выход'>
</form>

{% endblock body %}

artes/shop/templates/product.html
{% extends 'base.html' %}

{% block body %}
    {% for p in page_obj %}
    <hr></hr>
    <li>
        {{ p.title }}
        <p>URL: {{ p.slug }}
        <p>Категория: {{ p.cat }}
        <p>Подкатегория: {{ p.subcat }}
        <p>Цена: {{ p.price}} руб.
        <p><img src='{{ p.photo_m.url }}'>
        {% if is_auth %}
            <form action="{% url 'cart:add_cart' p.id 0%}" method="post">
                {{ cart_add_form }}
                {% csrf_token %}
                <input type="submit" value="Добавить в корзину">
            </form>
        {% endif %}
    </li>
    <hr></hr>
{% endfor %}
{% endblock body %}

artes/shop/templates/register.html
{% extends 'base.html' %}

{% block body %}

<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Регистрация</button>
</form>

{% endblock body %}