artes/artes/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from artes import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

artes/cart/urls.py
from .views import *
from django.urls import path

app_name='cart'
urlpatterns=[
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/<change>/', add_cart, name='add_cart'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('clear/', cart_clear, name='cart_clear')
]

artes/cart/models.py
from django.db import models

# Create your models here.

artes/cart/forms.py
from django import forms

choice_list=[(i, str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
    quantity=forms.TypedChoiceField(choices=choice_list, coerce=int, label='Количество')
    update=forms.BooleanField(required=False, widget=forms.HiddenInput, initial=False)

artes/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

menu = [{'title':'Вход', 'url_name':'shop:login'},
        {'title':'Регистрация', 'url_name':'shop:register'},
        {'title':'Категории товаров', 'url_name':'shop:category'},
        {'title':'Товары', 'url_name':'shop:product'},
        {'title':'Корзина', 'url_name':'cart:cart_detail'},
]
def add_cart(request, product_id, change):
    cart=Cart(request)
    product=get_object_or_404(Product, id=product_id)
    form=CartAddProductForm(request.POST)
    if str(product_id) in cart.cart.keys() and change!=0:
        cart.cart[str(product_id)]['quantity']+=int(change)
        cart.save()
    if form.is_valid():
        cd=form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            update_quantity=cd['update']
        )
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    if not request.user.is_authenticated:
        return redirect('shop:product')
    return render(request, 'details.html', {'cart': cart, 'title':'Корзина', 'menu':menu})

def cart_clear(request):
    cart=Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')

artes/cart/templates/details.html
{% extends 'base.html' %}

{% block body %}
    <table>
        <thead>
            <tr>
                <th>Фото</th>
                <th>Наименование</th>
                <th>Количество</th>
                <th>Удалить</th>
                <th>Цена товара</th>
                <th>Стоимость</th>
            </tr>

        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <img src="
                                {% if product.photo %}
                                    {{product.photo_s.url}}
                                {% else %}}
                                    <p>Нет изображения
                                {% endif %}">
                        </td>
                        <td>{{ product.title }}</td>
                        <td>
                        <a href="{% url 'cart:add_cart' product.id -1%}">&#10134;</a>
                            {{ item.quantity }}
                            <a href="{% url 'cart:add_cart' product.id 1%}">&#10133;</a>
                        </td>
                        <td align="center"><a href="{% url 'cart:cart_remove' product.id %}">&#128686;</a></td>
                        <td>{{ item.price }} руб.</td>
                        <td>{{ item.total_price}} руб.</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr>
                <td>Итого: </td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>{{ cart.get_total_price }} руб.</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td><a href="{% url 'cart:cart_clear' %}">Очистить корзину</a></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>
{% endblock body %}